CREATE TABLE article (
                         id integer NOT NULL,
                         content character varying(255),
                         create_at timestamp without time zone,
                         title character varying(255),
                         author_id integer
);


ALTER TABLE article OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 45336)
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 206 (class 1259 OID 45348)
-- Name: blogger_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE blogger_user (
                              id integer NOT NULL,
                              bio character varying(255),
                              display_name character varying(255),
                              password character varying(255),
                              username character varying(255)
);


ALTER TABLE blogger_user OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 45346)
-- Name: blogger_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE blogger_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME blogger_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 202 (class 1259 OID 44727)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE hibernate_sequence OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 45358)
-- Name: subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE subscription (
                              id integer NOT NULL,
                              followee_id integer,
                              follower_id integer
);


ALTER TABLE subscription OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 45356)
-- Name: subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 210 (class 1259 OID 45365)
-- Name: user_reaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE user_reaction (
                               id integer NOT NULL,
                               mark character varying(255),
                               article_id integer,
                               blogger_user_id integer
);


ALTER TABLE user_reaction OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 45363)
-- Name: user_reaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE user_reaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_reaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 2710 (class 2606 OID 45345)
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- TOC entry 2712 (class 2606 OID 45355)
-- Name: blogger_user blogger_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY blogger_user
    ADD CONSTRAINT blogger_user_pkey PRIMARY KEY (id);


--
-- TOC entry 2718 (class 2606 OID 45362)
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (id);


--
-- TOC entry 2714 (class 2606 OID 45373)
-- Name: blogger_user uk_2bxwscu1eididovbfw9085ek7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY blogger_user
    ADD CONSTRAINT uk_2bxwscu1eididovbfw9085ek7 UNIQUE (username);


--
-- TOC entry 2716 (class 2606 OID 45371)
-- Name: blogger_user uk_5xir9cnbbas9xradixq6xyj2i; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY blogger_user
    ADD CONSTRAINT uk_5xir9cnbbas9xradixq6xyj2i UNIQUE (display_name);


--
-- TOC entry 2720 (class 2606 OID 45375)
-- Name: user_reaction ukbddk2qwj53k1f45h9jq580uad; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY user_reaction
    ADD CONSTRAINT ukbddk2qwj53k1f45h9jq580uad UNIQUE (article_id, blogger_user_id);


--
-- TOC entry 2722 (class 2606 OID 45369)
-- Name: user_reaction user_reaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY user_reaction
    ADD CONSTRAINT user_reaction_pkey PRIMARY KEY (id);


--
-- TOC entry 2723 (class 2606 OID 45376)
-- Name: article fk69w79nosdcd3yw8ys0wjwg9dr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY article
    ADD CONSTRAINT fk69w79nosdcd3yw8ys0wjwg9dr FOREIGN KEY (author_id) REFERENCES blogger_user(id);


--
-- TOC entry 2727 (class 2606 OID 45396)
-- Name: user_reaction fkc0r31ykbmg9k6kuxswywga0u7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY user_reaction
    ADD CONSTRAINT fkc0r31ykbmg9k6kuxswywga0u7 FOREIGN KEY (blogger_user_id) REFERENCES blogger_user(id);


--
-- TOC entry 2725 (class 2606 OID 45386)
-- Name: subscription fkood05yh3qokliv1c8r8j7kybm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY subscription
    ADD CONSTRAINT fkood05yh3qokliv1c8r8j7kybm FOREIGN KEY (follower_id) REFERENCES blogger_user(id);


--
-- TOC entry 2724 (class 2606 OID 45381)
-- Name: subscription fktr0ga7v0u9ul3ytrtujr7ckpv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY subscription
    ADD CONSTRAINT fktr0ga7v0u9ul3ytrtujr7ckpv FOREIGN KEY (followee_id) REFERENCES blogger_user(id);


--
-- TOC entry 2726 (class 2606 OID 45391)
-- Name: user_reaction fkwiddeukub3fypapulunajvqf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY user_reaction
    ADD CONSTRAINT fkwiddeukub3fypapulunajvqf FOREIGN KEY (article_id) REFERENCES article(id);


-- Completed on 2021-04-08 17:28:43

--
-- PostgreSQL database dump complete
--

